version: '3.8'

services:
  db:
    container_name: woodcock_postgresql
    image: postgres:11.21-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
