[tool.poetry]
name = "woodcock"
version = "0.1.0"
description = "A scalable implementation of RDF2Vec"
authors = ["Kevin Haller <contact@kevinhaller.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pylint = "^2.17.4"
duckdb = "^0.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
