[tool.poetry]
name = "woodcock"
version = "0.1.0"
description = "A scalable implementation of RDF2Vec"
authors = ["Kevin Haller <contact@kevinhaller.dev>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.10"
duckdb = "^0.8.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
pylint = "^2.0.0"
pytest-mock = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
